- name: Set up debian package repository with reprepro
  hosts: localhost
  connection: local
  become: true

  vars:
    user_name: <USER> # Replace with your actual username

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - reprepro
          - nginx
        state: present

    - name: Create repository directory
      file:
        path: /var/www/html/debian
        state: directory

    - name: Copy repository packages
      copy:
        src: /home/{{ user_name }}/ansible/files/debian_packages/
        dest: /var/www/html/debian

    - name: Create repository conf directory
      file:
        path: /var/www/html/debian/conf
        state: directory

    - name: Copy repository conf
      copy:
        src: /home/{{ user_name }}/ansible/files/reprepro/distributions
        dest: /var/www/html/debian/conf/distributions

    - name: Initialize reprepro repository
      command: reprepro -b /var/www/html/debian includedeb bullseye /home/{{ user_name }}/ansible/files/debian_packages/*.deb
      args:
        creates:
          - /var/www/html/debian/dists/bullseye/main/binary-amd64/Packages
          - /var/www/html/debian/dists/bullseye/main/binary-arm64/Packages

    - name: Create Nginx virtual host
      template:
        src: /home/{{ user_name }}/ansible/files/nginx_config/nginx_repo.conf.j2
        dest: /etc/nginx/sites-available/repo
      notify: Reload Nginx

    - name: Enable Nginx virtual host
      file:
        src: /etc/nginx/sites-available/repo
        dest: /etc/nginx/sites-enabled/repo
        state: link
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
